
steps:
  - name: 'gcr.io/cloud-builders/go'
    args: ['build', './src/main.go']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/app:latest', '.']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'docker'
      - 'push'
      - 'gcr.io/$PROJECT_ID/app:latest'